### ISSUE TITLE
An interpretation of a period

### ISSUE THREAD

**Issue by ysaikai** [ysaikai/LFABM#5]
As far as all the dynamic equations and variables are consistent with an interpretation of each period, we can scale it whatever ways we like. I am about to start with a CSA module and we try to incorporate seasonality, which necessitates a meaning of periods. So far, we have put little meaning on either variable or equation. Let's start to pay some attention to it. Say,
&nbsp;&nbsp;&nbsp;one period = one week
Does this sound reasonable? For instance, we have the (dis)appearance rate of producers, roughly, one every 3 periods after the mass disappearance in the first 15 periods. If we see the grid representing an entire state, perhaps it makes some sense? Also, one unit of food means food for sustaining an average household for a week. Let's discuss.

**Comment by elansegarra** [comment]
I believe we can decide on whatever time frame we would like it to be (it is just a matter of parametrizing our variables correctly so that this time frame is consistent). One period = 1 week works for me as well since that fits nicely with the farmer's market model (they occur weekly after all) and one major food stop a week for food also sounds reasonable.
If after reparameterizing we still find that there is 1 producer dying every 3 weeks on average, that seems a bit high to me (but I do not actually have data handy to say either way). Checked up quickly ([source here](http://www.jsonline.com/business/number-of-farms-in-wisconsin-drops-11-percent-in-five-years-b99261135z1-257729721.html)) and in Wisconsin the number of farms has fallen about 2% every year, so weekly that is 0.038%, so if steady state in our model is 4-5 farms, then we should lose one farm every 5-6 weeks (periods) to be close to Wisconsin facts. We should probably do a similar calculation for new farms if we want to match real trends.
